export { default as BaseInput } from './BaseInput/BaseInput.vue'
export { default as BaseButton } from './BaseButton/BaseButton.vue'
export { default as BaseBreadcrumb } from './BaseBreadcrumb/BaseBreadcrumb.vue'
export { default as BaseCard } from './BaseCard/BaseCard.vue'
export { default as BaseTable } from './BaseTable/BaseTable.vue'
export { default as BasePagination } from './BasePagination/BasePagination.vue'
